Use Atestados;
INSERT INTO Rubro VALUES
('Libro', '', 1),
('Artículo', '', 1),
('Desarrollo de software', '', 1),
('Proyectos de graduación galardonados', '', 1),
('Obra didáctica', '', 1),
('Obra administrativa de desarrollo', '', 1),
('Otras obras profesionales', '', 1),
('Obras artísticas', '', 1),
('Proyectos de investigación y extensión', '', 2),
('Actividades para el fortalecimiento de la investigación y la extensión', '', 2),
('Patente de invención', '', 2),
('Cursos de educación continuada', '', 2),
('Capacitación interna', '', 2),
('Cursos libres', '', 2),
('Trabajo docente no remunerado de carreras del ITCR', '', 2),
('Premios nacionales e internacionales', '', 2),
('Membresía en Consejos Editoriales', '', 2),
('Membresía organismos extrainstitucionales', '', 2),
('Organización de eventos de proyección externa', '', 2),
('Participación destacada en eventos de proyección externa', '', 2),
('Colaboración en eventos externos', '', 2),
('Participación destacada en eventos deportivos', '', 2),
('Publicaciones y divulgaciones científicas y culturales en un medio de comunicación masiva', '', 2),
('Jurado de premios nacionales', '', 2),
('Modelo de Utilidad', '', 2),
('bis Proyectos de innovación docente', '', 2),
('Diseño industrial', '', 2),
('Modelo industrial', '', 2),
('Obtención vegetal', '', 2),
('Secreto', '', 2),
('Sistema de trazado de circuitos integrados', '', 2),
('Ponencia', '', 2),
('Grados académicos', '', 3),
('Idiomas', '', 3),
('Conocimiento y manejo de software', '', 3),
('Capacitación profesional', '', 3);