INSERT INTO Pais VALUES
('Afganistán'),
('Islas Åland'),
('Albania'),
('Alemania'),
('Andorra'),
('Angola'),
('Anguila'),
('Antártida'),
('Antigua Y Barbuda'),
('Arabia Saudita'),
('Argelia'),
('Argentina'),
('Armenia'),
('Aruba'),
('Australia'),
('Austria'),
('Azerbaiyán'),
('Bahamas'),
('Bangladés'),
('Barbados'),
('Baréin'),
('Bélgica'),
('Belice'),
('Benín'),
('Bermudas'),
('Bielorrusia'),
('Myanmar Nota 1'),
('Bolivia, Estado Plurinacional De'),
('Bosnia Y Herzegovina'),
('Botsuana'),
('Brasil'),
('Brunéi Darussalam'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Bután'),
('Cabo Verde'),
('Camboya'),
('Camerún'),
('Canadá'),
('Qatar'),
('Bonaire, San Eustaquio Y Saba'),
('Chad'),
('Chile'),
('China'),
('Chipre'),
('Colombia'),
('Comoras'),
('Corea, República Democrática Popular De'),
('Corea, República De'),
('Côte D''Ivoire'),
('Costa Rica'),
('Croacia'),
('Cuba'),
('Curaçao'),
('Dinamarca'),
('Dominica'),
('Ecuador'),
('Egipto'),
('El Salvador'),
('Emiratos Árabes Unidos'),
('Eritrea'),
('Eslovaquia'),
('Eslovenia'),
('España'),
('Estados Unidos'),
('Estonia'),
('Etiopía'),
('Filipinas'),
('Finlandia'),
('Fiyi'),
('Francia'),
('Gabón'),
('Gambia'),
('Georgia'),
('Ghana'),
('Gibraltar'),
('Granada'),
('Grecia'),
('Groenlandia'),
('Guadalupe'),
('Guam'),
('Guatemala'),
('Guayana Francesa'),
('Guernsey'),
('Guinea'),
('Guinea-Bisáu'),
('Guinea Ecuatorial'),
('Guyana'),
('Haití'),
('Honduras'),
('Hong Kong'),
('Hungría'),
('India'),
('Indonesia'),
('Irak'),
('Irán, República Islámica De'),
('Irlanda'),
('Isla Bouvet'),
('Isla De Man'),
('Isla De Navidad'),
('Isla Norfolk'),
('Islandia'),
('Islas Caimán'),
('Islas Cocos (Keeling)'),
('Islas Cook'),
('Islas Feroe'),
('Georgia Del Sur Y Las Islas Sandwich Del Sur'),
('Isla Heard E Islas Mcdonald'),
('Islas Falkland (Malvinas)'),
('Islas Marianas Del Norte'),
('Islas Marshall'),
('Pitcairn'),
('Islas Salomón'),
('Islas Turcas Y Caicos'),
('Islas Ultramarinas Menores De Estados Unidos'),
('Islas Vírgenes (Británicas)'),
('Islas Vírgenes (Ee.Uu.)'),
('Israel'),
('Italia'),
('Jamaica'),
('Japón'),
('Jersey'),
('Jordania'),
('Kazajistán'),
('Kenia'),
('Kirguistán'),
('Kiribati'),
('Kuwait'),
('Lao, República Democrática Popular'),
('Lesoto'),
('Letonia'),
('Líbano'),
('Liberia'),
('Libia'),
('Liechtenstein'),
('Lituania'),
('Luxemburgo'),
('Macao'),
('Madagascar'),
('Malasia'),
('Malaui'),
('Maldivas'),
('Malí'),
('Malta'),
('Marruecos'),
('Martinica'),
('Mauricio'),
('Mauritania'),
('Mayotte'),
('México'),
('Micronesia, Estados Federados De'),
('Moldavia, República De'),
('Mónaco'),
('Mongolia'),
('Montenegro'),
('Montserrat'),
('Mozambique'),
('Namibia'),
('Nauru'),
('Nepal'),
('Nicaragua'),
('Níger'),
('Nigeria'),
('Niue'),
('Noruega'),
('Nueva Caledonia'),
('Nueva Zelanda'),
('Omán'),
('Países Bajos'),
('Pakistán'),
('Palaos'),
('Palestina, Estado De'),
('Panamá'),
('Papúa Nueva Guinea'),
('Paraguay'),
('Perú'),
('Polinesia Francesa'),
('Polonia'),
('Portugal'),
('Puerto Rico'),
('Reino Unido'),
('República Centroafricana'),
('República Checa'),
('Macedonia, La Antigua República Yugoslava De'),
('Congo'),
('Congo, República Democrática Del'),
('República Dominicana'),
('Reunión'),
('Ruanda'),
('Rumania'),
('Rusia, Federación De'),
('Sahara Occidental'),
('Samoa'),
('Samoa Americana'),
('San Bartolomé'),
('San Cristóbal Y Nieves'),
('San Marino'),
('San Martín (Parte Francesa)'),
('San Pedro Y Miquelón'),
('San Vicente Y Las Granadinas'),
('Santa Helena, Ascensión Y Tristán De Acuña'),
('Santa Lucía'),
('Santo Tomé Y Príncipe'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leona'),
('Singapur'),
('Sint Maarten (Parte Neerlandesa)'),
('Siria, República Árabe'),
('Somalia'),
('Sri Lanka'),
('Suazilandia'),
('Sudáfrica'),
('Sudán'),
('Sudán Del Sur'),
('Suecia'),
('Suiza'),
('Surinam'),
('Svalbard Y Jan Mayen'),
('Tailandia'),
('Taiwán, Provincia De China'),
('Tanzania, República Unida De'),
('Tayikistán'),
('Territorio Británico Del Océano Índico'),
('Territorios Australes Franceses'),
('Timor-Leste'),
('Togo'),
('Tokelau'),
('Tonga'),
('Trinidad Y Tobago'),
('Túnez'),
('Turkmenistán'),
('Turquía'),
('Tuvalu'),
('Ucrania'),
('Uganda'),
('Uruguay'),
('Uzbekistán'),
('Vanuatu'),
('Santa Sede (Ciudad Estado Vaticano)'),
('Venezuela, República Bolivariana De'),
('Viet Nam'),
('Wallis Y Futuna'),
('Yemen'),
('Yibuti'),
('Zambia'),
('Zimbabue');