INSERT INTO Idioma VALUES
('afar'),
('abjasio (oabjasiano)'),
('avéstico'),
('afrikáans'),
('akano'),
('amhárico'),
('aragonés'),
('árabe'),
('asamés'),
('avar (oávaro)'),
('aimara'),
('azerí'),
('baskir'),
('bielorruso'),
('búlgaro'),
('bhoyapurí'),
('bislama'),
('bambara'),
('bengalí'),
('tibetano'),
('bretón'),
('bosnio'),
('catalán'),
('checheno'),
('chamorro'),
('corso'),
('cree'),
('checo'),
('eslavoeclesiásticoantiguo'),
('chuvasio'),
('galés'),
('danés'),
('alemán'),
('maldivo (odhivehi)'),
('dzongkha'),
('ewé'),
('griego(moderno)'),
('inglés'),
('esperanto'),
('español (ocastellano)'),
('estonio'),
('euskera'),
('persa'),
('fula'),
('finés (ofinlandés)'),
('fiyiano (ofiyi)'),
('feroés'),
('francés'),
('frisón (ofrisio)'),
('irlandés (ogaélico)'),
('gaélicoescocés'),
('gallego'),
('guaraní'),
('guyaratí (ogujaratí)'),
('manés (gaélicomanésodeIsladeMan)'),
('hausa'),
('hebreo'),
('hindi (ohindú)'),
('hirimotu'),
('croata'),
('haitiano'),
('húngaro'),
('armenio'),
('herero'),
('interlingua'),
('indonesio'),
('occidental'),
('igbo'),
('yideSichuán'),
('iñupiaq'),
('ido'),
('islandés'),
('italiano'),
('inuktitut (oinuit)'),
('japonés'),
('javanés'),
('georgiano'),
('kongo (okikongo)'),
('kikuyu'),
('kuanyama'),
('kazajo (okazajio)'),
('groenlandés (okalaallisut)'),
('camboyano (ojemer)'),
('canarés'),
('coreano'),
('kanuri'),
('cachemiro (ocachemir)'),
('kurdo'),
('komi'),
('córnico'),
('kirguís'),
('latín'),
('luxemburgués'),
('luganda'),
('limburgués'),
('lingala'),
('lao'),
('lituano'),
('luba-katanga (ochiluba)'),
('letón'),
('malgache (omalagasy)'),
('marshalés'),
('maorí'),
('macedonio'),
('malayalam'),
('mongol'),
('maratí'),
('malayo'),
('maltés'),
('birmano'),
('nauruano'),
('noruegobokmål'),
('ndebeledelnorte'),
('nepalí'),
('ndonga'),
('neerlandés (uholandés)'),
('nynorsk'),
('noruego'),
('ndebeledelsur'),
('navajo'),
('chichewa'),
('occitano'),
('ojibwa'),
('oromo'),
('oriya'),
('osético (uosetio,uoseta)'),
('panyabí (openyabi)'),
('pali'),
('polaco'),
('pastú (opastún,opashto)'),
('portugués'),
('quechua'),
('romanche'),
('kirundi'),
('rumano'),
('ruso'),
('ruandés (okiñaruanda)'),
('sánscrito'),
('sardo'),
('sindhi'),
('samiseptentrional'),
('sango'),
('cingalés'),
('eslovaco'),
('esloveno'),
('samoano'),
('shona'),
('somalí'),
('albanés'),
('serbio'),
('suazi (oswati,osiSwati)'),
('sesotho'),
('sundanés (osondanés)'),
('sueco'),
('suajili'),
('tamil'),
('télugu'),
('tayiko'),
('tailandés'),
('tigriña'),
('turcomano'),
('tagalo'),
('setsuana'),
('tongano'),
('turco'),
('tsonga'),
('tártaro'),
('twi'),
('tahitiano'),
('uigur'),
('ucraniano'),
('urdu'),
('uzbeko'),
('venda'),
('vietnamita'),
('volapük'),
('valón'),
('wolof'),
('xhosa'),
('yídish (oyidis,oyiddish)'),
('yoruba'),
('chuan (ochuang,ozhuang)'),
('chino'),
('zulú')
