//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.UIProcess.WCF_ServicioAtestados {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_ServicioAtestados.IServiciosAtestados")]
    public interface IServiciosAtestados {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosAtestados/ConsultarConfiguracion", ReplyAction="http://tempuri.org/IServiciosAtestados/ConsultarConfiguracionResponse")]
        Atestados.Objetos.Clases.oRespuesta<System.Collections.Generic.List<Atestados.Objetos.Clases.Configuracion>> ConsultarConfiguracion(System.Nullable<int> idConfiguracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosAtestados/ConsultarConfiguracion", ReplyAction="http://tempuri.org/IServiciosAtestados/ConsultarConfiguracionResponse")]
        System.Threading.Tasks.Task<Atestados.Objetos.Clases.oRespuesta<System.Collections.Generic.List<Atestados.Objetos.Clases.Configuracion>>> ConsultarConfiguracionAsync(System.Nullable<int> idConfiguracion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosAtestadosChannel : Atestados.UIProcess.WCF_ServicioAtestados.IServiciosAtestados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosAtestadosClient : System.ServiceModel.ClientBase<Atestados.UIProcess.WCF_ServicioAtestados.IServiciosAtestados>, Atestados.UIProcess.WCF_ServicioAtestados.IServiciosAtestados {
        
        public ServiciosAtestadosClient() {
        }
        
        public ServiciosAtestadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosAtestadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosAtestadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosAtestadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Atestados.Objetos.Clases.oRespuesta<System.Collections.Generic.List<Atestados.Objetos.Clases.Configuracion>> ConsultarConfiguracion(System.Nullable<int> idConfiguracion) {
            return base.Channel.ConsultarConfiguracion(idConfiguracion);
        }
        
        public System.Threading.Tasks.Task<Atestados.Objetos.Clases.oRespuesta<System.Collections.Generic.List<Atestados.Objetos.Clases.Configuracion>>> ConsultarConfiguracionAsync(System.Nullable<int> idConfiguracion) {
            return base.Channel.ConsultarConfiguracionAsync(idConfiguracion);
        }
    }
}
