//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public int ArchivoID { get; set; }
        public int Obligatorio { get; set; }
        public string Nombre { get; set; }
        public byte[] Datos { get; set; }
        public string TipoArchivo { get; set; }
        public int AtestadoID { get; set; }
    
        public virtual Atestado Atestado { get; set; }
    }
}
