//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public int ArchivoID { get; set; }
        public int Obligatorio { get; set; }
        public string Nombre { get; set; }
        public byte[] Datos { get; set; }
        public string TipoArchivo { get; set; }
        public int AtestadoID { get; set; }
    
        public virtual Atestado Atestado { get; set; }
    }
}
