//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.Datos.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AtestadosEntities : DbContext
    {
        public AtestadosEntities()
            : base("name=AtestadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archivo> Archivo { get; set; }
        public virtual DbSet<Atestado> Atestado { get; set; }
        public virtual DbSet<AtestadoXPersona> AtestadoXPersona { get; set; }
        public virtual DbSet<DominioIdioma> DominioIdioma { get; set; }
        public virtual DbSet<Fecha> Fecha { get; set; }
        public virtual DbSet<Idioma> Idioma { get; set; }
        public virtual DbSet<InfoEditorial> InfoEditorial { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Rubro> Rubro { get; set; }
        public virtual DbSet<TipoRubro> TipoRubro { get; set; }
    }
}
