//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atestado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atestado()
        {
            this.AtestadoXPersonas = new HashSet<AtestadoXPersona>();
            this.DominioIdiomas = new HashSet<DominioIdioma>();
        }
    
        public int AtestadoID { get; set; }
        public string Nombre { get; set; }
        public int NumeroAutores { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime HoraCreacion { get; set; }
        public Nullable<int> Enviado { get; set; }
        public Nullable<int> Descargado { get; set; }
        public Nullable<int> CantidadHoras { get; set; }
        public string Lugar { get; set; }
        public string CatalogoTipo { get; set; }
        public string Enlace { get; set; }
        public Nullable<int> PaisID { get; set; }
        public Nullable<int> PersonaID { get; set; }
        public Nullable<int> RubroID { get; set; }
    
        public virtual Pai Pai { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Rubro Rubro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtestadoXPersona> AtestadoXPersonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DominioIdioma> DominioIdiomas { get; set; }
    }
}
