//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DominioIdioma
    {
        public int DominioIdiomaID { get; set; }
        public Nullable<int> IdiomaID { get; set; }
        public int Lectura { get; set; }
        public int Escrito { get; set; }
        public int Auditiva { get; set; }
        public int Oral { get; set; }
    
        public virtual Atestado Atestado { get; set; }
        public virtual Idioma Idioma { get; set; }
    }
}
