//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoEditorial
    {
        public int InfoEditorialID { get; set; }
        public string Editorial { get; set; }
        public string Website { get; set; }
    
        public virtual Atestado Atestado { get; set; }
    }
}
