//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.WCF.WCF_Email {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecAdjunto", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class TecAdjunto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoArchivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Archivo {
            get {
                return this.ArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoField, value) != true)) {
                    this.ArchivoField = value;
                    this.RaisePropertyChanged("Archivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreArchivo {
            get {
                return this.NombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArchivoField, value) != true)) {
                    this.NombreArchivoField = value;
                    this.RaisePropertyChanged("NombreArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoArchivo {
            get {
                return this.TipoArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoArchivoField, value) != true)) {
                    this.TipoArchivoField = value;
                    this.RaisePropertyChanged("TipoArchivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecRespuesta", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class TecRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRespuesta {
            get {
                return this.CodigoRespuestaField;
            }
            set {
                if ((this.CodigoRespuestaField.Equals(value) != true)) {
                    this.CodigoRespuestaField = value;
                    this.RaisePropertyChanged("CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecEntidades", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class TecEntidades : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecEntidad> ListadoEntidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRespuesta {
            get {
                return this.CodigoRespuestaField;
            }
            set {
                if ((this.CodigoRespuestaField.Equals(value) != true)) {
                    this.CodigoRespuestaField = value;
                    this.RaisePropertyChanged("CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecEntidad> ListadoEntidades {
            get {
                return this.ListadoEntidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.ListadoEntidadesField, value) != true)) {
                    this.ListadoEntidadesField = value;
                    this.RaisePropertyChanged("ListadoEntidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecEntidad", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class TecEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoEntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Atestados.WCF.WCF_Email.CuentaCorreoExtendida> ListadoCuentasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEntidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoEntidad {
            get {
                return this.CodigoEntidadField;
            }
            set {
                if ((this.CodigoEntidadField.Equals(value) != true)) {
                    this.CodigoEntidadField = value;
                    this.RaisePropertyChanged("CodigoEntidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Atestados.WCF.WCF_Email.CuentaCorreoExtendida> ListadoCuentas {
            get {
                return this.ListadoCuentasField;
            }
            set {
                if ((object.ReferenceEquals(this.ListadoCuentasField, value) != true)) {
                    this.ListadoCuentasField = value;
                    this.RaisePropertyChanged("ListadoCuentas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEntidad {
            get {
                return this.NombreEntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEntidadField, value) != true)) {
                    this.NombreEntidadField = value;
                    this.RaisePropertyChanged("NombreEntidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaCorreoExtendida", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class CuentaCorreoExtendida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaPrincipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoCuentaPrincipalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Contador {
            get {
                return this.ContadorField;
            }
            set {
                if ((this.ContadorField.Equals(value) != true)) {
                    this.ContadorField = value;
                    this.RaisePropertyChanged("Contador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuenta {
            get {
                return this.CuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaField, value) != true)) {
                    this.CuentaField = value;
                    this.RaisePropertyChanged("Cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaPrincipal {
            get {
                return this.CuentaPrincipalField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaPrincipalField, value) != true)) {
                    this.CuentaPrincipalField = value;
                    this.RaisePropertyChanged("CuentaPrincipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstadoCuenta {
            get {
                return this.EstadoCuentaField;
            }
            set {
                if ((this.EstadoCuentaField.Equals(value) != true)) {
                    this.EstadoCuentaField = value;
                    this.RaisePropertyChanged("EstadoCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstadoCuentaPrincipal {
            get {
                return this.EstadoCuentaPrincipalField;
            }
            set {
                if ((this.EstadoCuentaPrincipalField.Equals(value) != true)) {
                    this.EstadoCuentaPrincipalField = value;
                    this.RaisePropertyChanged("EstadoCuentaPrincipal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecBitacora", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class TecBitacora : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Atestados.WCF.WCF_Email.Bitacora> ListadoBitacoraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRespuesta {
            get {
                return this.CodigoRespuestaField;
            }
            set {
                if ((this.CodigoRespuestaField.Equals(value) != true)) {
                    this.CodigoRespuestaField = value;
                    this.RaisePropertyChanged("CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Atestados.WCF.WCF_Email.Bitacora> ListadoBitacora {
            get {
                return this.ListadoBitacoraField;
            }
            set {
                if ((object.ReferenceEquals(this.ListadoBitacoraField, value) != true)) {
                    this.ListadoBitacoraField = value;
                    this.RaisePropertyChanged("ListadoBitacora");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bitacora", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class Bitacora : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuerpoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinatariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroDestinatariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuerpo {
            get {
                return this.CuerpoField;
            }
            set {
                if ((object.ReferenceEquals(this.CuerpoField, value) != true)) {
                    this.CuerpoField = value;
                    this.RaisePropertyChanged("Cuerpo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destinatarios {
            get {
                return this.DestinatariosField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinatariosField, value) != true)) {
                    this.DestinatariosField = value;
                    this.RaisePropertyChanged("Destinatarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpOrigen {
            get {
                return this.IpOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.IpOrigenField, value) != true)) {
                    this.IpOrigenField = value;
                    this.RaisePropertyChanged("IpOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metodo {
            get {
                return this.MetodoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodoField, value) != true)) {
                    this.MetodoField = value;
                    this.RaisePropertyChanged("Metodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroDestinatarios {
            get {
                return this.NumeroDestinatariosField;
            }
            set {
                if ((this.NumeroDestinatariosField.Equals(value) != true)) {
                    this.NumeroDestinatariosField = value;
                    this.RaisePropertyChanged("NumeroDestinatarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecCorreosNoEnviados", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class TecCorreosNoEnviados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecCorreoFormatoBitacora> ListadoCorreosNoEnviadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRespuesta {
            get {
                return this.CodigoRespuestaField;
            }
            set {
                if ((this.CodigoRespuestaField.Equals(value) != true)) {
                    this.CodigoRespuestaField = value;
                    this.RaisePropertyChanged("CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecCorreoFormatoBitacora> ListadoCorreosNoEnviados {
            get {
                return this.ListadoCorreosNoEnviadosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListadoCorreosNoEnviadosField, value) != true)) {
                    this.ListadoCorreosNoEnviadosField = value;
                    this.RaisePropertyChanged("ListadoCorreosNoEnviados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecCorreoFormatoBitacora", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class TecCorreoFormatoBitacora : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoEnviadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuerpoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinatariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdBitacoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroDestinatariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoEnviador {
            get {
                return this.CorreoEnviadorField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoEnviadorField, value) != true)) {
                    this.CorreoEnviadorField = value;
                    this.RaisePropertyChanged("CorreoEnviador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuerpo {
            get {
                return this.CuerpoField;
            }
            set {
                if ((object.ReferenceEquals(this.CuerpoField, value) != true)) {
                    this.CuerpoField = value;
                    this.RaisePropertyChanged("Cuerpo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destinatarios {
            get {
                return this.DestinatariosField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinatariosField, value) != true)) {
                    this.DestinatariosField = value;
                    this.RaisePropertyChanged("Destinatarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBitacora {
            get {
                return this.IdBitacoraField;
            }
            set {
                if ((this.IdBitacoraField.Equals(value) != true)) {
                    this.IdBitacoraField = value;
                    this.RaisePropertyChanged("IdBitacora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoMovimiento {
            get {
                return this.IdTipoMovimientoField;
            }
            set {
                if ((this.IdTipoMovimientoField.Equals(value) != true)) {
                    this.IdTipoMovimientoField = value;
                    this.RaisePropertyChanged("IdTipoMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpOrigen {
            get {
                return this.IpOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.IpOrigenField, value) != true)) {
                    this.IpOrigenField = value;
                    this.RaisePropertyChanged("IpOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metodo {
            get {
                return this.MetodoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodoField, value) != true)) {
                    this.MetodoField = value;
                    this.RaisePropertyChanged("Metodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroDestinatarios {
            get {
                return this.NumeroDestinatariosField;
            }
            set {
                if ((this.NumeroDestinatariosField.Equals(value) != true)) {
                    this.NumeroDestinatariosField = value;
                    this.RaisePropertyChanged("NumeroDestinatarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecRespuestaCuenta", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class TecRespuestaCuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atestados.WCF.WCF_Email.CuentaCorreo CuentaCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atestados.WCF.WCF_Email.CuentaCorreo CuentaCorreo {
            get {
                return this.CuentaCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaCorreoField, value) != true)) {
                    this.CuentaCorreoField = value;
                    this.RaisePropertyChanged("CuentaCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaCorreo", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class CuentaCorreo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int contadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int instanciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int contador {
            get {
                return this.contadorField;
            }
            set {
                if ((this.contadorField.Equals(value) != true)) {
                    this.contadorField = value;
                    this.RaisePropertyChanged("contador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaField, value) != true)) {
                    this.contrasenaField = value;
                    this.RaisePropertyChanged("contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int instancias {
            get {
                return this.instanciasField;
            }
            set {
                if ((this.instanciasField.Equals(value) != true)) {
                    this.instanciasField = value;
                    this.RaisePropertyChanged("instancias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecCorreosEnviar", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class TecCorreosEnviar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> ListaAdjuntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecFormatoCorreo> ListaCorreosEnviarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRespuesta {
            get {
                return this.CodigoRespuestaField;
            }
            set {
                if ((this.CodigoRespuestaField.Equals(value) != true)) {
                    this.CodigoRespuestaField = value;
                    this.RaisePropertyChanged("CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> ListaAdjuntos {
            get {
                return this.ListaAdjuntosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaAdjuntosField, value) != true)) {
                    this.ListaAdjuntosField = value;
                    this.RaisePropertyChanged("ListaAdjuntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecFormatoCorreo> ListaCorreosEnviar {
            get {
                return this.ListaCorreosEnviarField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaCorreosEnviarField, value) != true)) {
                    this.ListaCorreosEnviarField = value;
                    this.RaisePropertyChanged("ListaCorreosEnviar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecFormatoCorreo", Namespace="http://schemas.datacontract.org/2004/07/TEC.Email.Objetos.Clases")]
    [System.SerializableAttribute()]
    public partial class TecFormatoCorreo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoEnviadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuerpoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnviadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsHtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdColaCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrioridadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoEnviador {
            get {
                return this.CorreoEnviadorField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoEnviadorField, value) != true)) {
                    this.CorreoEnviadorField = value;
                    this.RaisePropertyChanged("CorreoEnviador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuerpo {
            get {
                return this.CuerpoField;
            }
            set {
                if ((object.ReferenceEquals(this.CuerpoField, value) != true)) {
                    this.CuerpoField = value;
                    this.RaisePropertyChanged("Cuerpo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destinatario {
            get {
                return this.DestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinatarioField, value) != true)) {
                    this.DestinatarioField = value;
                    this.RaisePropertyChanged("Destinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enviado {
            get {
                return this.EnviadoField;
            }
            set {
                if ((this.EnviadoField.Equals(value) != true)) {
                    this.EnviadoField = value;
                    this.RaisePropertyChanged("Enviado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsHtml {
            get {
                return this.EsHtmlField;
            }
            set {
                if ((this.EsHtmlField.Equals(value) != true)) {
                    this.EsHtmlField = value;
                    this.RaisePropertyChanged("EsHtml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdColaCorreo {
            get {
                return this.IdColaCorreoField;
            }
            set {
                if ((this.IdColaCorreoField.Equals(value) != true)) {
                    this.IdColaCorreoField = value;
                    this.RaisePropertyChanged("IdColaCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prioridad {
            get {
                return this.PrioridadField;
            }
            set {
                if ((object.ReferenceEquals(this.PrioridadField, value) != true)) {
                    this.PrioridadField = value;
                    this.RaisePropertyChanged("Prioridad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_Email.IEmail")]
    public interface IEmail {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/EnviarCorreo", ReplyAction="http://tempuri.org/IEmail/EnviarCorreoResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta EnviarCorreo(string destinatario, string cc, string cco, string asunto, string cuerpo, bool html, string prioridad, string usuario, string password, System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> listaAdjuntos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/EnviarCorreo", ReplyAction="http://tempuri.org/IEmail/EnviarCorreoResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> EnviarCorreoAsync(string destinatario, string cc, string cco, string asunto, string cuerpo, bool html, string prioridad, string usuario, string password, System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> listaAdjuntos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/EnviarCorreoMasivo", ReplyAction="http://tempuri.org/IEmail/EnviarCorreoMasivoResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta EnviarCorreoMasivo(System.Collections.Generic.List<string> listaDestinatarios, string asunto, string cuerpo, bool html, string prioridad, string usuario, string password, System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> listaAdjuntos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/EnviarCorreoMasivo", ReplyAction="http://tempuri.org/IEmail/EnviarCorreoMasivoResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> EnviarCorreoMasivoAsync(System.Collections.Generic.List<string> listaDestinatarios, string asunto, string cuerpo, bool html, string prioridad, string usuario, string password, System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> listaAdjuntos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/InsertarCuentaCorreoPadre", ReplyAction="http://tempuri.org/IEmail/InsertarCuentaCorreoPadreResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta InsertarCuentaCorreoPadre(string cuentaCorreo, string contrasena, int codigoEntidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/InsertarCuentaCorreoPadre", ReplyAction="http://tempuri.org/IEmail/InsertarCuentaCorreoPadreResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> InsertarCuentaCorreoPadreAsync(string cuentaCorreo, string contrasena, int codigoEntidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/InsertarCorreoSistema", ReplyAction="http://tempuri.org/IEmail/InsertarCorreoSistemaResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta InsertarCorreoSistema(string cuentaCorreo, string contrasena, string cuentaCorreoPadre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/InsertarCorreoSistema", ReplyAction="http://tempuri.org/IEmail/InsertarCorreoSistemaResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> InsertarCorreoSistemaAsync(string cuentaCorreo, string contrasena, string cuentaCorreoPadre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarEntidadesCuentas", ReplyAction="http://tempuri.org/IEmail/ConsultarEntidadesCuentasResponse")]
        Atestados.WCF.WCF_Email.TecEntidades ConsultarEntidadesCuentas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarEntidadesCuentas", ReplyAction="http://tempuri.org/IEmail/ConsultarEntidadesCuentasResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecEntidades> ConsultarEntidadesCuentasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/InsertarEntidad", ReplyAction="http://tempuri.org/IEmail/InsertarEntidadResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta InsertarEntidad(string entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/InsertarEntidad", ReplyAction="http://tempuri.org/IEmail/InsertarEntidadResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> InsertarEntidadAsync(string entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ModificaEstadoCuentaPadre", ReplyAction="http://tempuri.org/IEmail/ModificaEstadoCuentaPadreResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta ModificaEstadoCuentaPadre(string cuentaCorreo, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ModificaEstadoCuentaPadre", ReplyAction="http://tempuri.org/IEmail/ModificaEstadoCuentaPadreResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> ModificaEstadoCuentaPadreAsync(string cuentaCorreo, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ModificaEstadoCuentaCorreo", ReplyAction="http://tempuri.org/IEmail/ModificaEstadoCuentaCorreoResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta ModificaEstadoCuentaCorreo(string cuentaCorreo, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ModificaEstadoCuentaCorreo", ReplyAction="http://tempuri.org/IEmail/ModificaEstadoCuentaCorreoResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> ModificaEstadoCuentaCorreoAsync(string cuentaCorreo, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ModificaContrasenaCorreoSistema", ReplyAction="http://tempuri.org/IEmail/ModificaContrasenaCorreoSistemaResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta ModificaContrasenaCorreoSistema(string cuentaCorreo, string contrasena, string contrasena_anterior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ModificaContrasenaCorreoSistema", ReplyAction="http://tempuri.org/IEmail/ModificaContrasenaCorreoSistemaResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> ModificaContrasenaCorreoSistemaAsync(string cuentaCorreo, string contrasena, string contrasena_anterior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ModificaContrasenaCuentaPadre", ReplyAction="http://tempuri.org/IEmail/ModificaContrasenaCuentaPadreResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta ModificaContrasenaCuentaPadre(string cuentaCorreo, string contrasena, string contrasena_anterior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ModificaContrasenaCuentaPadre", ReplyAction="http://tempuri.org/IEmail/ModificaContrasenaCuentaPadreResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> ModificaContrasenaCuentaPadreAsync(string cuentaCorreo, string contrasena, string contrasena_anterior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarBitacoraPorCorreoSistema", ReplyAction="http://tempuri.org/IEmail/ConsultarBitacoraPorCorreoSistemaResponse")]
        Atestados.WCF.WCF_Email.TecBitacora ConsultarBitacoraPorCorreoSistema(string cuenta, System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarBitacoraPorCorreoSistema", ReplyAction="http://tempuri.org/IEmail/ConsultarBitacoraPorCorreoSistemaResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecBitacora> ConsultarBitacoraPorCorreoSistemaAsync(string cuenta, System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarBitacoraPorCuentaPadre", ReplyAction="http://tempuri.org/IEmail/ConsultarBitacoraPorCuentaPadreResponse")]
        Atestados.WCF.WCF_Email.TecBitacora ConsultarBitacoraPorCuentaPadre(string cuenta, System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarBitacoraPorCuentaPadre", ReplyAction="http://tempuri.org/IEmail/ConsultarBitacoraPorCuentaPadreResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecBitacora> ConsultarBitacoraPorCuentaPadreAsync(string cuenta, System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarBitacoraPorEntidad", ReplyAction="http://tempuri.org/IEmail/ConsultarBitacoraPorEntidadResponse")]
        Atestados.WCF.WCF_Email.TecBitacora ConsultarBitacoraPorEntidad(int idEntidad, System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarBitacoraPorEntidad", ReplyAction="http://tempuri.org/IEmail/ConsultarBitacoraPorEntidadResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecBitacora> ConsultarBitacoraPorEntidadAsync(int idEntidad, System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ModificaEntidad", ReplyAction="http://tempuri.org/IEmail/ModificaEntidadResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta ModificaEntidad(int idEntidad, string nombreEntidad, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ModificaEntidad", ReplyAction="http://tempuri.org/IEmail/ModificaEntidadResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> ModificaEntidadAsync(int idEntidad, string nombreEntidad, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarCorreosNoEnviados", ReplyAction="http://tempuri.org/IEmail/ConsultarCorreosNoEnviadosResponse")]
        Atestados.WCF.WCF_Email.TecCorreosNoEnviados ConsultarCorreosNoEnviados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarCorreosNoEnviados", ReplyAction="http://tempuri.org/IEmail/ConsultarCorreosNoEnviadosResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecCorreosNoEnviados> ConsultarCorreosNoEnviadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarCuentaPadreAPartirHijo", ReplyAction="http://tempuri.org/IEmail/ConsultarCuentaPadreAPartirHijoResponse")]
        Atestados.WCF.WCF_Email.TecRespuestaCuenta ConsultarCuentaPadreAPartirHijo(string correoHijo, string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarCuentaPadreAPartirHijo", ReplyAction="http://tempuri.org/IEmail/ConsultarCuentaPadreAPartirHijoResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuestaCuenta> ConsultarCuentaPadreAPartirHijoAsync(string correoHijo, string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ActualizarExitoFlujoAlterno", ReplyAction="http://tempuri.org/IEmail/ActualizarExitoFlujoAlternoResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta ActualizarExitoFlujoAlterno(int idBitacora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ActualizarExitoFlujoAlterno", ReplyAction="http://tempuri.org/IEmail/ActualizarExitoFlujoAlternoResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> ActualizarExitoFlujoAlternoAsync(int idBitacora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarCorreosXEnviar", ReplyAction="http://tempuri.org/IEmail/ConsultarCorreosXEnviarResponse")]
        Atestados.WCF.WCF_Email.TecCorreosEnviar ConsultarCorreosXEnviar(string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ConsultarCorreosXEnviar", ReplyAction="http://tempuri.org/IEmail/ConsultarCorreosXEnviarResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecCorreosEnviar> ConsultarCorreosXEnviarAsync(string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/DesmarcarEnviadoCola", ReplyAction="http://tempuri.org/IEmail/DesmarcarEnviadoColaResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta DesmarcarEnviadoCola(int idCola, string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/DesmarcarEnviadoCola", ReplyAction="http://tempuri.org/IEmail/DesmarcarEnviadoColaResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> DesmarcarEnviadoColaAsync(int idCola, string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/EnviadorMensajesMasivosExclusivoWinService", ReplyAction="http://tempuri.org/IEmail/EnviadorMensajesMasivosExclusivoWinServiceResponse")]
        Atestados.WCF.WCF_Email.TecRespuesta EnviadorMensajesMasivosExclusivoWinService(string listaDestinatarios, string asunto, string cuerpo, bool html, string prioridad, string usuario, string password, System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> listaAdjuntos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/EnviadorMensajesMasivosExclusivoWinService", ReplyAction="http://tempuri.org/IEmail/EnviadorMensajesMasivosExclusivoWinServiceResponse")]
        System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> EnviadorMensajesMasivosExclusivoWinServiceAsync(string listaDestinatarios, string asunto, string cuerpo, bool html, string prioridad, string usuario, string password, System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> listaAdjuntos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailChannel : Atestados.WCF.WCF_Email.IEmail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailClient : System.ServiceModel.ClientBase<Atestados.WCF.WCF_Email.IEmail>, Atestados.WCF.WCF_Email.IEmail {
        
        public EmailClient() {
        }
        
        public EmailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta EnviarCorreo(string destinatario, string cc, string cco, string asunto, string cuerpo, bool html, string prioridad, string usuario, string password, System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> listaAdjuntos) {
            return base.Channel.EnviarCorreo(destinatario, cc, cco, asunto, cuerpo, html, prioridad, usuario, password, listaAdjuntos);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> EnviarCorreoAsync(string destinatario, string cc, string cco, string asunto, string cuerpo, bool html, string prioridad, string usuario, string password, System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> listaAdjuntos) {
            return base.Channel.EnviarCorreoAsync(destinatario, cc, cco, asunto, cuerpo, html, prioridad, usuario, password, listaAdjuntos);
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta EnviarCorreoMasivo(System.Collections.Generic.List<string> listaDestinatarios, string asunto, string cuerpo, bool html, string prioridad, string usuario, string password, System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> listaAdjuntos) {
            return base.Channel.EnviarCorreoMasivo(listaDestinatarios, asunto, cuerpo, html, prioridad, usuario, password, listaAdjuntos);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> EnviarCorreoMasivoAsync(System.Collections.Generic.List<string> listaDestinatarios, string asunto, string cuerpo, bool html, string prioridad, string usuario, string password, System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> listaAdjuntos) {
            return base.Channel.EnviarCorreoMasivoAsync(listaDestinatarios, asunto, cuerpo, html, prioridad, usuario, password, listaAdjuntos);
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta InsertarCuentaCorreoPadre(string cuentaCorreo, string contrasena, int codigoEntidad) {
            return base.Channel.InsertarCuentaCorreoPadre(cuentaCorreo, contrasena, codigoEntidad);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> InsertarCuentaCorreoPadreAsync(string cuentaCorreo, string contrasena, int codigoEntidad) {
            return base.Channel.InsertarCuentaCorreoPadreAsync(cuentaCorreo, contrasena, codigoEntidad);
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta InsertarCorreoSistema(string cuentaCorreo, string contrasena, string cuentaCorreoPadre) {
            return base.Channel.InsertarCorreoSistema(cuentaCorreo, contrasena, cuentaCorreoPadre);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> InsertarCorreoSistemaAsync(string cuentaCorreo, string contrasena, string cuentaCorreoPadre) {
            return base.Channel.InsertarCorreoSistemaAsync(cuentaCorreo, contrasena, cuentaCorreoPadre);
        }
        
        public Atestados.WCF.WCF_Email.TecEntidades ConsultarEntidadesCuentas() {
            return base.Channel.ConsultarEntidadesCuentas();
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecEntidades> ConsultarEntidadesCuentasAsync() {
            return base.Channel.ConsultarEntidadesCuentasAsync();
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta InsertarEntidad(string entidad) {
            return base.Channel.InsertarEntidad(entidad);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> InsertarEntidadAsync(string entidad) {
            return base.Channel.InsertarEntidadAsync(entidad);
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta ModificaEstadoCuentaPadre(string cuentaCorreo, bool estado) {
            return base.Channel.ModificaEstadoCuentaPadre(cuentaCorreo, estado);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> ModificaEstadoCuentaPadreAsync(string cuentaCorreo, bool estado) {
            return base.Channel.ModificaEstadoCuentaPadreAsync(cuentaCorreo, estado);
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta ModificaEstadoCuentaCorreo(string cuentaCorreo, bool estado) {
            return base.Channel.ModificaEstadoCuentaCorreo(cuentaCorreo, estado);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> ModificaEstadoCuentaCorreoAsync(string cuentaCorreo, bool estado) {
            return base.Channel.ModificaEstadoCuentaCorreoAsync(cuentaCorreo, estado);
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta ModificaContrasenaCorreoSistema(string cuentaCorreo, string contrasena, string contrasena_anterior) {
            return base.Channel.ModificaContrasenaCorreoSistema(cuentaCorreo, contrasena, contrasena_anterior);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> ModificaContrasenaCorreoSistemaAsync(string cuentaCorreo, string contrasena, string contrasena_anterior) {
            return base.Channel.ModificaContrasenaCorreoSistemaAsync(cuentaCorreo, contrasena, contrasena_anterior);
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta ModificaContrasenaCuentaPadre(string cuentaCorreo, string contrasena, string contrasena_anterior) {
            return base.Channel.ModificaContrasenaCuentaPadre(cuentaCorreo, contrasena, contrasena_anterior);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> ModificaContrasenaCuentaPadreAsync(string cuentaCorreo, string contrasena, string contrasena_anterior) {
            return base.Channel.ModificaContrasenaCuentaPadreAsync(cuentaCorreo, contrasena, contrasena_anterior);
        }
        
        public Atestados.WCF.WCF_Email.TecBitacora ConsultarBitacoraPorCorreoSistema(string cuenta, System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.ConsultarBitacoraPorCorreoSistema(cuenta, fechaInicio, fechaFin);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecBitacora> ConsultarBitacoraPorCorreoSistemaAsync(string cuenta, System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.ConsultarBitacoraPorCorreoSistemaAsync(cuenta, fechaInicio, fechaFin);
        }
        
        public Atestados.WCF.WCF_Email.TecBitacora ConsultarBitacoraPorCuentaPadre(string cuenta, System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.ConsultarBitacoraPorCuentaPadre(cuenta, fechaInicio, fechaFin);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecBitacora> ConsultarBitacoraPorCuentaPadreAsync(string cuenta, System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.ConsultarBitacoraPorCuentaPadreAsync(cuenta, fechaInicio, fechaFin);
        }
        
        public Atestados.WCF.WCF_Email.TecBitacora ConsultarBitacoraPorEntidad(int idEntidad, System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.ConsultarBitacoraPorEntidad(idEntidad, fechaInicio, fechaFin);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecBitacora> ConsultarBitacoraPorEntidadAsync(int idEntidad, System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.ConsultarBitacoraPorEntidadAsync(idEntidad, fechaInicio, fechaFin);
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta ModificaEntidad(int idEntidad, string nombreEntidad, bool estado) {
            return base.Channel.ModificaEntidad(idEntidad, nombreEntidad, estado);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> ModificaEntidadAsync(int idEntidad, string nombreEntidad, bool estado) {
            return base.Channel.ModificaEntidadAsync(idEntidad, nombreEntidad, estado);
        }
        
        public Atestados.WCF.WCF_Email.TecCorreosNoEnviados ConsultarCorreosNoEnviados() {
            return base.Channel.ConsultarCorreosNoEnviados();
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecCorreosNoEnviados> ConsultarCorreosNoEnviadosAsync() {
            return base.Channel.ConsultarCorreosNoEnviadosAsync();
        }
        
        public Atestados.WCF.WCF_Email.TecRespuestaCuenta ConsultarCuentaPadreAPartirHijo(string correoHijo, string usuario, string pass) {
            return base.Channel.ConsultarCuentaPadreAPartirHijo(correoHijo, usuario, pass);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuestaCuenta> ConsultarCuentaPadreAPartirHijoAsync(string correoHijo, string usuario, string pass) {
            return base.Channel.ConsultarCuentaPadreAPartirHijoAsync(correoHijo, usuario, pass);
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta ActualizarExitoFlujoAlterno(int idBitacora) {
            return base.Channel.ActualizarExitoFlujoAlterno(idBitacora);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> ActualizarExitoFlujoAlternoAsync(int idBitacora) {
            return base.Channel.ActualizarExitoFlujoAlternoAsync(idBitacora);
        }
        
        public Atestados.WCF.WCF_Email.TecCorreosEnviar ConsultarCorreosXEnviar(string usuario, string pass) {
            return base.Channel.ConsultarCorreosXEnviar(usuario, pass);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecCorreosEnviar> ConsultarCorreosXEnviarAsync(string usuario, string pass) {
            return base.Channel.ConsultarCorreosXEnviarAsync(usuario, pass);
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta DesmarcarEnviadoCola(int idCola, string usuario, string pass) {
            return base.Channel.DesmarcarEnviadoCola(idCola, usuario, pass);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> DesmarcarEnviadoColaAsync(int idCola, string usuario, string pass) {
            return base.Channel.DesmarcarEnviadoColaAsync(idCola, usuario, pass);
        }
        
        public Atestados.WCF.WCF_Email.TecRespuesta EnviadorMensajesMasivosExclusivoWinService(string listaDestinatarios, string asunto, string cuerpo, bool html, string prioridad, string usuario, string password, System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> listaAdjuntos) {
            return base.Channel.EnviadorMensajesMasivosExclusivoWinService(listaDestinatarios, asunto, cuerpo, html, prioridad, usuario, password, listaAdjuntos);
        }
        
        public System.Threading.Tasks.Task<Atestados.WCF.WCF_Email.TecRespuesta> EnviadorMensajesMasivosExclusivoWinServiceAsync(string listaDestinatarios, string asunto, string cuerpo, bool html, string prioridad, string usuario, string password, System.Collections.Generic.List<Atestados.WCF.WCF_Email.TecAdjunto> listaAdjuntos) {
            return base.Channel.EnviadorMensajesMasivosExclusivoWinServiceAsync(listaDestinatarios, asunto, cuerpo, html, prioridad, usuario, password, listaAdjuntos);
        }
    }
}
