//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.Utilitarios.Mensajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atestados.Utilitarios.Mensajes.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemas procesando la solicitud. Intentarlo más tarde..
        /// </summary>
        public static string MensajeGenerico {
            get {
                return ResourceManager.GetString("MensajeGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar algún mensaje acá.
        /// </summary>
        public static string MensajeNuevo {
            get {
                return ResourceManager.GetString("MensajeNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de correo no es correcto..
        /// </summary>
        public static string Atestados_EmailInvalido {
            get {
                return ResourceManager.GetString("Atestados_EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de correo no es correcto, solamente direcciones de correo TEC..
        /// </summary>
        public static string Atestados_EmailInvalidoTEC {
            get {
                return ResourceManager.GetString("Atestados_EmailInvalidoTEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de ejecución del servicio..
        /// </summary>
        public static string Atestados_ErrordeEjecucion {
            get {
                return ResourceManager.GetString("Atestados_ErrordeEjecucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al generar el token de acceso..
        /// </summary>
        public static string Atestados_ErrorGeneracionToken {
            get {
                return ResourceManager.GetString("Atestados_ErrorGeneracionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La lista no puede ser vacía..
        /// </summary>
        public static string Atestados_ListaVacia {
            get {
                return ResourceManager.GetString("Atestados_ListaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto tiene valores incorrectos..
        /// </summary>
        public static string Atestados_ObjetoInvalido {
            get {
                return ResourceManager.GetString("Atestados_ObjetoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros de entrada inválidos..
        /// </summary>
        public static string Atestados_Parametros_invalidos {
            get {
                return ResourceManager.GetString("Atestados_Parametros_invalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no debe ser mayor de 32 carácteres..
        /// </summary>
        public static string Atestados_PasswordInvalido {
            get {
                return ResourceManager.GetString("Atestados_PasswordInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///    &lt;html lang=&quot;es&quot;&gt;
        ///
        ///    &lt;head&gt;
        ///
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///
        ///        &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1.0&quot;&gt;
        ///
        ///        &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto&quot; rel=&quot;stylesheet&quot;&gt;
        ///
        ///        &lt;style&gt;
        ///
        ///       
        ///
        ///            body{
        ///
        ///                font-family: &apos;&apos;Helvetica Regular&apos;&apos;, Helvetica, &apos;&apos;Roboto&apos;&apos;, sans-serif, Arial;
        ///
        ///                font [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AtestadosCorreo {
            get {
                return ResourceManager.GetString("AtestadosCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña ingresada posee caracteres inválidos..
        /// </summary>
        public static string ValidacionCaracteresContrasena {
            get {
                return ResourceManager.GetString("ValidacionCaracteresContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ingresado posee caracteres inválidos..
        /// </summary>
        public static string ValidacionCaracteresUsuario {
            get {
                return ResourceManager.GetString("ValidacionCaracteresUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos no pueden ser nulos..
        /// </summary>
        public static string ValidacionNulos {
            get {
                return ResourceManager.GetString("ValidacionNulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No posee permisos para utilizar este método. Revisar los datos suministrados Usuario y Contraseña..
        /// </summary>
        public static string ValidacionPermisosMetodo {
            get {
                return ResourceManager.GetString("ValidacionPermisosMetodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no posee permisos activos en la aplicación..
        /// </summary>
        public static string ValidacionPermisosUsuario {
            get {
                return ResourceManager.GetString("ValidacionPermisosUsuario", resourceCulture);
            }
        }
    }
}
